import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Providers from "@/lib/Providers";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";


export const metadata: Metadata = {
  title: "Techzon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-scroll="0">
    <Providers>
      <body>
        <Toaster position="bottom-right" richColors />
        <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
      </body>
    </Providers>

  </html>
  );
}
