name: Node.js Deployment with NGINX and SSL

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            set -e

            # Variables
            PROJECT_DIR="/var/www/html/zrf/client"
            client_CONF="/etc/nginx/sites-available/client.zrf.info"
            PROJECT_CONF="$PROJECT_DIR/nginx.conf"

            # Navigate to project directory
            cd $PROJECT_DIR

            # Clone the repository if not exists
            if [ ! -d ".git" ]; then
              git clone git@github.com:SoftyPy-IT/ziaurrahmanfoundation.git .
            fi

            # Fetch latest changes and reset to main branch
            git fetch --all
            git reset --hard origin/main

            # Setup environment and dependencies
            cp .env.example .env

            npm install --legacy-peer-deps
            npm run build

            # Deploy NGINX Configuration Conditionally
            if ! diff -q "$PROJECT_CONF" "$client_CONF" > /dev/null; then
              echo "NGINX configuration has changed. Updating..."
              sudo cp "$PROJECT_CONF" "$client_CONF"
              sudo ln -sf "$client_CONF" /etc/nginx/sites-enabled/client.zrf.info

            # Ensure symbolic link exists in sites-enabled
              if [ ! -f "/etc/nginx/sites-enabled/client.zrf.info" ]; then
              sudo ln -sf "$client_CONF" /etc/nginx/sites-enabled/client.zrf.info
              fi

              # Test and reload NGINX
              sudo nginx -t && sudo systemctl reload nginx
            else
              echo "NGINX configuration is unchanged. Skipping update."
            fi

            # Manage SSL using Certbot

              sudo certbot --nginx -d zrf.info -d www.zrf.info --non-interactive --agree-tos --register-unsafely-without-email

            # Manage PM2 process
            if pm2 list | grep -q "sub.softypy.com"; then
              echo "PM2 process already exists. Restarting..."
              pm2 restart sub.softypy.com
            else
              echo "No PM2 process found. Starting..."
              pm2 start npm --name "sub.softypy.com" -- start
            fi

            # Save PM2 process list
            pm2 save
