name: Deploy Live Chat Frontend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up SSH for GitHub Actions
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          ssh-keyscan -t rsa ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      # Step 3: Test SSH connection
      - name: Test SSH connection
        run: |
          ssh -vvv -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} "echo 'SSH connection successful'"

      # Step 4: Deploy to VPS using SSH
      - name: Deploy to VPS using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          timeout: 60s
          script: |
            set -e
            echo "Starting deployment..."
            
            # Variables
            PROJECT_DIR="/var/www/techzon2"
            NGINX_CONF="/etc/nginx/sites-available/chatapp.muissa.com.conf"
            PROJECT_NGINX_CONF="$PROJECT_DIR/nginx.conf"
            GIT_URL="https://github.com/Ibrahim-Sikder/techzon2.git"
            DOMAIN_NAME="chatapp.muissa.com"
            
            # Ensure project directory exists
            sudo mkdir -p $PROJECT_DIR
            sudo chown -R $USER:$USER $PROJECT_DIR
            
            cd $PROJECT_DIR
            
            # Clone or update repository
            if [ ! -d ".git" ]; then
              git clone $GIT_URL .
            else
              git fetch --all
              git reset --hard origin/main
            fi
            
            # Install dependencies and build
            npm install --legacy-peer-deps
            npm run build
            
            # Update NGINX configuration
            if [ -f "$PROJECT_NGINX_CONF" ]; then
              sudo cp "$PROJECT_NGINX_CONF" "$NGINX_CONF"
              sudo ln -sf "$NGINX_CONF" /etc/nginx/sites-enabled/
              sudo nginx -t && sudo systemctl reload nginx
            fi
            
            # Manage PM2 process
            if pm2 list | grep -q "techzon2"; then
              pm2 restart techzon2
            else
              pm2 start npm --name "techzon2" -- start
            fi
            
            pm2 save
            echo "Deployment completed successfully!"