name: Deploy Live Chat Frontend with NGINX and SSL

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            set -e

            # Variables
            PROJECT_DIR="/var/www/techzon2"
            NGINX_CONF="/etc/nginx/sites-available/chatapp.muissa.com.conf"
            PROJECT_NGINX_CONF="$PROJECT_DIR/nginx.conf"
            GIT_URL="https://github.com/Ibrahim-Sikder/techzon2.git"
            DOMAIN_NAME="chatapp.muissa.com"

            # Navigate to project directory
            if [ ! -d "$PROJECT_DIR" ]; then
              sudo mkdir -p $PROJECT_DIR
              sudo chown -R $USER:$USER $PROJECT_DIR
            fi
            cd $PROJECT_DIR

            # Clone the repository if not exists
            if [ ! -d ".git" ]; then
              git clone $GIT_URL .
            fi

            # Fetch latest changes and reset to main branch
            git fetch --all
            git reset --hard origin/main

            # Setup environment and dependencies
            if [ ! -f ".env" ]; then
              cp .env.example .env
            fi

            npm install --legacy-peer-deps
            npm run build

            # Deploy NGINX Configuration Conditionally
            if ! diff -q "$PROJECT_NGINX_CONF" "$NGINX_CONF" > /dev/null; then
              echo "NGINX configuration has changed. Updating..."
              sudo cp "$PROJECT_NGINX_CONF" "$NGINX_CONF"

              # Ensure symbolic link exists in sites-enabled
              if [ ! -f "/etc/nginx/sites-enabled/chatapp.muissa.com.conf" ]; then
                sudo ln -sf "$NGINX_CONF" /etc/nginx/sites-enabled/chatapp.muissa.com.conf
              fi

              # Test and reload NGINX
              sudo nginx -t && sudo systemctl reload nginx
            else
              echo "NGINX configuration is unchanged. Skipping update."
            fi

            # Manage SSL using Certbot for your domain
            sudo certbot --nginx -d $DOMAIN_NAME --non-interactive --agree-tos --register-unsafely-without-email

            # Manage PM2 process
            if pm2 list | grep -q "techzon2"; then
              echo "PM2 process already exists. Restarting..."
              pm2 restart techzon2
            else
              echo "No PM2 process found. Starting..."
              pm2 start npm --name "techzon2" -- start
            fi

            # Save PM2 process list
            pm2 save
