name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Referencing the secret SSH key

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no user@your-vps-ip "cd /path/to/your/project && git pull && npm install && pm2 restart all"
